version: '3.4'

volumes:
  redis_volume:

services:
  db:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    restart: always
    env_file:
      - ./.envs/.local/.postgres
  rmq:
    image: 'rabbitmq:3.8'
    ports:
      - "15672:15672"
      - "5672:5672"
      - "5671:5671"
    env_file:
      - ./.envs/.local/.rmq
  redis:
    image: redis:6.2-alpine
    volumes:
      - redis_volume:/data
    ports:
      - 6379:6379
    command:
      - 'redis-server'
      - '--save 300 50'
      - '--save 60 500'
  web:
    build:
      context: .
      dockerfile: compose/web/Dockerfile
    image: 'mop_test'
    restart: always
    volumes:
      - ./:/code
    links:
      - db
      - rmq
    command: /start
    env_file:
      - ./.envs/.local/.web
      - ./.envs/.local/.rmq
      - ./.envs/.local/.postgres
  worker:
    image: 'mop_test'
    restart: always
    volumes:
      - ".:/code"
    links:
      - db
      - rmq
    command: /start-worker
    env_file:
      - ./.envs/.local/.web
      - ./.envs/.local/.rmq
      - ./.envs/.local/.postgres
  beat:
    image: 'mop_test'
    restart: always
    volumes:
      - .:/code
    links:
      - db
      - rmq
    command: /start-beat
    depends_on:
      - web
    env_file:
      - ./.envs/.local/.web
      - ./.envs/.local/.rmq
      - ./.envs/.local/.postgres
  nginx:
    build:
      context: .
      dockerfile: compose/nginx/Dockerfile
    ports:
      - 8001:8001
    volumes:
      - .:/code
      - ./compose/nginx/local.conf:/etc/nginx/conf.d/default.conf
      - ./media:/media
      - ./static:/static
    depends_on:
      - web