# Generated by Django 3.1.5 on 2022-03-20 18:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('symbol', models.IntegerField(choices=[(0, 'AAPL'), (1, 'TWTR'), (2, 'GOLD'), (3, 'INTC')])),
            ],
        ),
    ]
