RSS_FEED_UTIL_URL = 'https://feeds.finance.yahoo.com/rss/2.0/headline?region=US&lang=en-US'
RSS_FEED_UTIL_AGENT = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36'

RSS_FEED_UTIL_SYMBOL_AAPL = 'AAPL'
RSS_FEED_UTIL_SYMBOL_TWTR = 'TWTR'
RSS_FEED_UTIL_SYMBOL_GOLD = 'GOLD'
RSS_FEED_UTIL_SYMBOL_INTC = 'INTC'

RSS_FEED_UTIL_SYMBOLS = [
    RSS_FEED_UTIL_SYMBOL_AAPL,
    RSS_FEED_UTIL_SYMBOL_TWTR,
    RSS_FEED_UTIL_SYMBOL_GOLD,
    RSS_FEED_UTIL_SYMBOL_INTC
]