#!/bin/sh

set -o errexit
set -o nounset

python manage.py migrate django_celery_beat

python manage.py migrate

python manage.py collectstatic --noinput

python -m uvicorn mop_test.asgi:application --host 0.0.0.0 --port 8000 --reload
