from scraper.constants.rss_feed_util import RSS_FEED_UTIL_SYMBOL_AAPL, RSS_FEED_UTIL_SYMBOL_GOLD, \
    RSS_FEED_UTIL_SYMBOL_TWTR, RSS_FEED_UTIL_SYMBOL_INTC

RSS_FEED_UTIL_SYMBOL_TYPE_AAPL = 0
RSS_FEED_UTIL_SYMBOL_TYPE_TWTR = 1
RSS_FEED_UTIL_SYMBOL_TYPE_GOLD = 2
RSS_FEED_UTIL_SYMBOL_TYPE_INTC = 3

RSS_FEED_TYPES = (
    (RSS_FEED_UTIL_SYMBOL_TYPE_AAPL, RSS_FEED_UTIL_SYMBOL_AAPL),
    (RSS_FEED_UTIL_SYMBOL_TYPE_TWTR, RSS_FEED_UTIL_SYMBOL_TWTR),
    (RSS_FEED_UTIL_SYMBOL_TYPE_GOLD, RSS_FEED_UTIL_SYMBOL_GOLD),
    (RSS_FEED_UTIL_SYMBOL_TYPE_INTC, RSS_FEED_UTIL_SYMBOL_INTC)
)
